updated Kolab:Winterfell to latest version from OBS (20170508)

diff --git a/libkolab/debian/php-kolab.postinst b/libkolab/debian/php-kolab.postinst
--- a/libkolab/debian/php-kolab.postinst
+++ b/libkolab/debian/php-kolab.postinst
@@ -7,6 +7,8 @@ set -e
 
 if [ -d "/etc/php5/mods-available" ]; then
     inidir=/etc/php5/mods-available
+elif [ -d "/etc/php/mods-available" ]; then
+    inidir=/etc/php/mods-available
 else
     inidir=/etc/php5/conf.d
 fi
@@ -35,9 +37,11 @@ if [ "$1" = "configure" ]; then
 	fi
 
 	# Enable the module
-    if [ -x "$(which php5enmod 2>/dev/null)" ]; then
-    	php5enmod ${module}/${priority:-19}
-    fi
+	if [ -x "$(which $php5enmod 2>/dev/null)" ]; then
+	    php5enmod ${module}/${priority:-19}
+	elif [ -x "$(which $phpenmod 2>/dev/null)" ]; then
+	    phpenmod ${module}/${priority:-19}
+	fi
 fi
 # End dummy plugin
 
@@ -64,16 +68,18 @@ if [ "$1" = "configure" ]; then
 	fi
 
 	# Enable the module
-    if [ -x "$(which php5enmod 2>/dev/null)" ]; then
-    	php5enmod ${module}/${priority:-21}
-    fi
+	if [ -x "$(which $php5enmod 2>/dev/null)" ]; then
+	    php5enmod ${module}/${priority:-21}
+	elif [ -x "$(which $phpenmod 2>/dev/null)" ]; then
+	    phpenmod ${module}/${priority:-21}
+	fi
 fi
 
 if [ "$1" = "configure" ]; then
 
 	# make sure that kolabformat.so is loaded after dummy.so, see #2050
-	sed -i "s/extension=dummy.so/extension=dummy.so\nextension=kolabformat.so/" /usr/share/php5/kolab/kolab.ini
-	sed -i "s/extension=kolabformat.so/;extension=kolabformat.so/" /usr/share/php5/kolab/kolabformat.ini
+	sed -i "s/extension=dummy.so/extension=dummy.so\nextension=kolabformat.so/" $inidir/kolab.ini || echo "cannot find $inidir/kolab.ini"
+	sed -i "s/extension=kolabformat.so/;extension=kolabformat.so/" $inidir/kolabformat.ini || echo "cannot find $inidir/kolabformat.ini"
 
 fi
 
